alias ello="echo hello world"
alias cls="colorls"
alias fab="tmuxifier load-session fab"
alias geni="cd ~/Repos/fabric-platform/frontend/ && npm run genIndexes"
alias piper="cd ~/Repos/fabric-devops/ && make proxy"
